//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CleanArchitecture.Core.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class MsgResource_VN {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MsgResource_VN() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CleanArchitecture.Core.Resources.MsgResource_VN", typeof(MsgResource_VN).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xảy ra lỗi trong quá trình thêm, vui lòng thử lại sau hoặc liên hệ Thắng để được hỗ trợ.
        /// </summary>
        public static string AddErr {
            get {
                return ResourceManager.GetString("AddErr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thêm thành công.
        /// </summary>
        public static string AddSuccess {
            get {
                return ResourceManager.GetString("AddSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xác thực thành công.
        /// </summary>
        public static string AuthenticateSuccess {
            get {
                return ResourceManager.GetString("AuthenticateSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không thể xác thực.
        /// </summary>
        public static string CannotAuthorize {
            get {
                return ResourceManager.GetString("CannotAuthorize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không thể định dạng mã nhân viên.
        /// </summary>
        public static string CannotFormatEmployeeCode {
            get {
                return ResourceManager.GetString("CannotFormatEmployeeCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Có lỗi xảy ra,vui lòng thử lại hoặc liên hệ Thắng để được trợ giúp.
        /// </summary>
        public static string CommonErrr {
            get {
                return ResourceManager.GetString("CommonErrr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer code không được phép trông.
        /// </summary>
        public static string CustomerCodeCannotBeNull {
            get {
                return ResourceManager.GetString("CustomerCodeCannotBeNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã khách hàng không tồn tại.
        /// </summary>
        public static string CustomerCodeDoesNotExist {
            get {
                return ResourceManager.GetString("CustomerCodeDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã khách hàng không được trùng.
        /// </summary>
        public static string CustomerCodeDuplicate {
            get {
                return ResourceManager.GetString("CustomerCodeDuplicate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhóm mã khách hàng này không tồn tại, vui lòng kiểm tra lại.
        /// </summary>
        public static string CustomerGroupDoesNotExist {
            get {
                return ResourceManager.GetString("CustomerGroupDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã Nhóm khách hàng đã tồn tại.
        /// </summary>
        public static string CustomerGroupIdDuplicate {
            get {
                return ResourceManager.GetString("CustomerGroupIdDuplicate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên nhóm mã khách hàng không được để trống.
        /// </summary>
        public static string CustomerGroupNameCouldNotBeNull {
            get {
                return ResourceManager.GetString("CustomerGroupNameCouldNotBeNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã định danh khách hàng không được trùng.
        /// </summary>
        public static string CustomerIdDuplicate {
            get {
                return ResourceManager.GetString("CustomerIdDuplicate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không tìm thấy khách hàng trong hệ thống.
        /// </summary>
        public static string CustomerNotFound {
            get {
                return ResourceManager.GetString("CustomerNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to - Ngày sinh phải theo định dạng dd/MM/yyyy..
        /// </summary>
        public static string DateWrongFormat {
            get {
                return ResourceManager.GetString("DateWrongFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Có lỗi xảy ra trong quá trình xóa, vui lòng thử lại sau hoặc liên hệ Thắng để được hỗ trợ.
        /// </summary>
        public static string DeleteErr {
            get {
                return ResourceManager.GetString("DeleteErr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xóa thành công.
        /// </summary>
        public static string DeleteSucess {
            get {
                return ResourceManager.GetString("DeleteSucess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email không được trùng.
        /// </summary>
        public static string EmailDuplicate {
            get {
                return ResourceManager.GetString("EmailDuplicate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &gt; đã tồn tại trong hệ thống, vui lòng kiểm tra lại..
        /// </summary>
        public static string EmpCodeDoNotExistBack {
            get {
                return ResourceManager.GetString("EmpCodeDoNotExistBack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã Nhân viên &lt;.
        /// </summary>
        public static string EmpCodeDoNotExistFront {
            get {
                return ResourceManager.GetString("EmpCodeDoNotExistFront", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &gt; đã tồn tại trong hệ thống..
        /// </summary>
        public static string EmpFileCodeDoNotExistBack {
            get {
                return ResourceManager.GetString("EmpFileCodeDoNotExistBack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã nhân viên không tồn tại.
        /// </summary>
        public static string EmployeeCodeDoesNotExist {
            get {
                return ResourceManager.GetString("EmployeeCodeDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã nhân viên không được trùng.
        /// </summary>
        public static string EmployeeCodeDuplicate {
            get {
                return ResourceManager.GetString("EmployeeCodeDuplicate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to - 6 ký tự cuối mã mà nhân viên phải là số..
        /// </summary>
        public static string EmployeeCodeRule {
            get {
                return ResourceManager.GetString("EmployeeCodeRule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhân viên này không tồn tại.
        /// </summary>
        public static string EmployeeDoNotExist {
            get {
                return ResourceManager.GetString("EmployeeDoNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to - Tên đơn vị Không được để trống.
        /// </summary>
        public static string EmployeeFile_DepartmentNameIsRequired {
            get {
                return ResourceManager.GetString("EmployeeFile_DepartmentNameIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to - Tên đơn vị không hợp lệ..
        /// </summary>
        public static string EmployeeFile_DepartmentNotValid {
            get {
                return ResourceManager.GetString("EmployeeFile_DepartmentNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to - Mã Nhân viên không được để trống..
        /// </summary>
        public static string EmployeeFile_EmployeeCodeCanNotBeNull {
            get {
                return ResourceManager.GetString("EmployeeFile_EmployeeCodeCanNotBeNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã nhân viên không hợp lệ.
        /// </summary>
        public static string EmployeeFile_EmployeeCodeNotValid {
            get {
                return ResourceManager.GetString("EmployeeFile_EmployeeCodeNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cấu trúc file không đúng, hãy xem file mẫu để biết thêm chi tiết.
        /// </summary>
        public static string EmployeeFile_FileNotValid {
            get {
                return ResourceManager.GetString("EmployeeFile_FileNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File phải theo định dạng .xlsx, Hãy xem file mẫu để biết thêm chi tiết.
        /// </summary>
        public static string EmployeeFile_FileWrongFormat {
            get {
                return ResourceManager.GetString("EmployeeFile_FileWrongFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to - Tên Nhân viên không được để trống..
        /// </summary>
        public static string EmployeeFIle_NameIsRequired {
            get {
                return ResourceManager.GetString("EmployeeFIle_NameIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã định danh nhân viên đã tồn tại.
        /// </summary>
        public static string EmployeeIdAlreadyExist {
            get {
                return ResourceManager.GetString("EmployeeIdAlreadyExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã định danh nhân viên không được trùng.
        /// </summary>
        public static string EmployeeIdDuplicate {
            get {
                return ResourceManager.GetString("EmployeeIdDuplicate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên không được để trống.
        /// </summary>
        public static string EmployeeNameCannotBeNull {
            get {
                return ResourceManager.GetString("EmployeeNameCannotBeNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã nhân viên không tồn tại.
        /// </summary>
        public static string EmployeeNotFound {
            get {
                return ResourceManager.GetString("EmployeeNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không có phần tử nào trong danh sách nhân viên.
        /// </summary>
        public static string EmptyEmployeeList {
            get {
                return ResourceManager.GetString("EmptyEmployeeList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã nhân viên tối đa là 15 ký tự..
        /// </summary>
        public static string EployeeCodeLong {
            get {
                return ResourceManager.GetString("EployeeCodeLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhóm mã khách hàng không hợp lệ.
        /// </summary>
        public static string File_CustomerGroupInvalid {
            get {
                return ResourceManager.GetString("File_CustomerGroupInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngày sinh sai định dạng.
        /// </summary>
        public static string File_DobInvalid {
            get {
                return ResourceManager.GetString("File_DobInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã khách hàng đã tồn tại trên tệp nhập khẩu.
        /// </summary>
        public static string File_DuplicateCustomerCode {
            get {
                return ResourceManager.GetString("File_DuplicateCustomerCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số điện thoại đã tồn tại .
        /// </summary>
        public static string File_DuplicatePhoneNumber {
            get {
                return ResourceManager.GetString("File_DuplicatePhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File không được để trống.
        /// </summary>
        public static string FileNotValid {
            get {
                return ResourceManager.GetString("FileNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sửa lỗi để nhập khẩu thành công.
        /// </summary>
        public static string FixErrorToImport {
            get {
                return ResourceManager.GetString("FixErrorToImport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đã xảy ra lỗi trong quá trình tìm kiếm, vui lòng liên hệ Thắng hoặc thử lại sau.
        /// </summary>
        public static string FoundErr {
            get {
                return ResourceManager.GetString("FoundErr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không có bản ghi nào trong cơ sở dữ liệu.
        /// </summary>
        public static string GetEmpty {
            get {
                return ResourceManager.GetString("GetEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lấy ra không thành công, vui lòng thử lại sau hoặc liên hệ Thắng để được hỗ trợ.
        /// </summary>
        public static string GetErr {
            get {
                return ResourceManager.GetString("GetErr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lấy thành công.
        /// </summary>
        public static string GetSuccess {
            get {
                return ResourceManager.GetString("GetSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh token không hợp lệ.
        /// </summary>
        public static string InValidRefreshToken {
            get {
                return ResourceManager.GetString("InValidRefreshToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access token hoặc Refresh token không hợp lệ.
        /// </summary>
        public static string InvalidToken {
            get {
                return ResourceManager.GetString("InvalidToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username không tồn tại.
        /// </summary>
        public static string InvalidUserName {
            get {
                return ResourceManager.GetString("InvalidUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đăng xuất thành công.
        /// </summary>
        public static string LogoutSuccess {
            get {
                return ResourceManager.GetString("LogoutSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số trang phải &gt;0.
        /// </summary>
        public static string PagingErr {
            get {
                return ResourceManager.GetString("PagingErr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số điện thoại không được trùng.
        /// </summary>
        public static string PhoneNumberDuplicate {
            get {
                return ResourceManager.GetString("PhoneNumberDuplicate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vị trí này không tồn tại, vui lòng chọn vị trí khác.
        /// </summary>
        public static string PositionIdDoesntExist {
            get {
                return ResourceManager.GetString("PositionIdDoesntExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cập nhật thành công.
        /// </summary>
        public static string String1 {
            get {
                return ResourceManager.GetString("String1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tạo mới token thành công.
        /// </summary>
        public static string TokenCreationSuccess {
            get {
                return ResourceManager.GetString("TokenCreationSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Token không được phép null.
        /// </summary>
        public static string TokenModelIsNull {
            get {
                return ResourceManager.GetString("TokenModelIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Có lỗi xảy ra trong quá trình cập nhật, vui lòng thử lại sau hoặc liên hệ Thắng để được hỗ trợ.
        /// </summary>
        public static string UpdateErr {
            get {
                return ResourceManager.GetString("UpdateErr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cập nhật thành công.
        /// </summary>
        public static string UpdateSuccess {
            get {
                return ResourceManager.GetString("UpdateSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload file không thành công, vui lòng liên hệ Thắng để được hỗ trợ.
        /// </summary>
        public static string UpLoadFailed {
            get {
                return ResourceManager.GetString("UpLoadFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload file thành công.
        /// </summary>
        public static string UploadSuccess {
            get {
                return ResourceManager.GetString("UploadSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Người dùng đã tồn tại.
        /// </summary>
        public static string UserAlreadySuccess {
            get {
                return ResourceManager.GetString("UserAlreadySuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tạo người dùng không thành công, vui lòng thử lại.
        /// </summary>
        public static string UserCreateFailed {
            get {
                return ResourceManager.GetString("UserCreateFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tạo người dùng thành công .
        /// </summary>
        public static string UserCreateSuccess {
            get {
                return ResourceManager.GetString("UserCreateSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hợp lệ.
        /// </summary>
        public static string Valid {
            get {
                return ResourceManager.GetString("Valid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File phải đúng định dạng .xlsx.
        /// </summary>
        public static string Wrong_File_format {
            get {
                return ResourceManager.GetString("Wrong File format", resourceCulture);
            }
        }
    }
}
